version: "3.8"
services:
  api:
    build: ./backend
    container_name: backend_c
    environment:
      - MONGODB_URL=${MONGODB_URL}
      - HOST=0.0.0.0
      - PORT=5000
    image: mdsaif0872/backend:latest
    depends_on:
      - mongo
      - caddy
  frontend:
    build: ./frontend
    container_name: frontend_c
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    stdin_open: true
    tty: true
    image: mdsaif0872/frontend:latest
    depends_on:
      - caddy
  mongo:
    image: mongo:latest
    container_name: mongo_c
    volumes:
      - mongo_data:/data/db
  caddy:
    image: caddy:latest
    container_name: caddy_c
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
volumes:
  mongo_data:
  caddy_data:
  caddy_config:




# version: "3.8"
# services:
#   api:
#     build: ./backend
#     container_name: backend_c
#     environment:
#       - MONGODB_URL=${MONGODB_URL}
#       - HOST=0.0.0.0
#       - PORT=5000
#     image: mdsaif0872/backend:latest
#     depends_on:
#       - mongo
#       - caddy
#   frontend:
#     build: ./frontend
#     container_name: frontend_c
#     environment:
#       - HOST=0.0.0.0
#       - PORT=3000
#     stdin_open: true
#     tty: true
#     image: mdsaif0872/frontend:latest
#     depends_on:
#       - caddy
#   mongo:
#     image: mongo:latest
#     container_name: mongo_c

#   caddy:
#     image: caddy:latest
#     container_name: caddy_c
#     ports:
#       - 80:80
#       - 443:443
#     volumes:
#       - ./Caddyfile:/etc/caddy/Caddyfile
# volumes:
#   mongo_data:
#   caddy_data:
#   caddy_config: